env:
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
rules:
  no-inner-declarations: off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/camelcase': on
  '@typescript-eslint/explicit-function-return-type': on
  '@typescript-eslint/no-use-before-define': on

parserOptions:
  ecmaVersion: 2018
  sourceType: module